import React from "react";
import oph from "../../../assets/images/oph.jpg";

const DataTable = ({ data }) => {
  return (
    <div
      id="source-html"
      style={{
        width: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: "1rem",
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        {/* <img src={oph} alt="" style={{ width: "4rem", height: "auto" }} /> */}
        <h1
          style={{
            textAlign: "center",
            fontWeight: "bold",
            fontSize: "1.5rem",
            lineHeight: "2rem",
          }}
          className=" text-2xl"
        >
          Optimum Pension House
        </h1>
      </div>

      <div>
        <p>from January to February</p>
      </div>
      <table
        style={{
          width: "100%",
          borderCollapse: "collapse",
          border: "1px solid black",
          color: "#000",
        }}
      >
        <thead>
          <tr style={{ fontWeight: "bold", backgroundColor: "#f3f4f6" }}>
            <th
              style={{
                border: "1px solid #000",
                padding: "8px",
                textAlign: "left",
              }}
            >
              Date
            </th>
            <th
              style={{
                border: "1px solid #000",
                padding: "8px",
                textAlign: "left",
              }}
            >
              Quantity
            </th>
            <th
              style={{
                border: "1px solid #000",
                padding: "8px",
                textAlign: "left",
              }}
            >
              Room type
            </th>
            <th
              style={{
                border: "1px solid #000",
                padding: "8px",
                textAlign: "left",
              }}
            >
              Amount
            </th>
            <th
              style={{
                border: "1px solid #000",
                padding: "8px",
                textAlign: "left",
              }}
            >
              Total Amount
            </th>
          </tr>
        </thead>

        <tbody>
          {data.map((item, index) => (
            <tr key={index}>
              <td
                style={{
                  border: "1px solid #000",
                  padding: "8px",
                  textAlign: "left",
                }}
              >
                {item.date}
              </td>
              <td
                style={{
                  border: "1px solid #000",
                  padding: "8px",
                  textAlign: "left",
                }}
              >
                {item.quantity}
              </td>
              <td
                style={{
                  border: "1px solid #000",
                  padding: "8px",
                  textAlign: "left",
                }}
              >
                {item.roomType}
              </td>
              <td
                style={{
                  border: "1px solid #000",
                  padding: "8px",
                  textAlign: "left",
                }}
              >
                {item.amount}
              </td>
              <td
                style={{
                  border: "1px solid #000",
                  padding: "8px",
                  textAlign: "left",
                }}
              >
                {item.totalAmount}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="w-full flex items-center justify-end px-32 mt-4">
        <p style={{ textAlign: "right" }}>
          Total Profit:{" "}
          <span style={{ textDecoration: "underline" }}>$200</span>
        </p>
      </div>
      <div className="w-full flex items-center justify-end px-28">
        <div>
          <p style={{ textAlign: "right" }}>
            Generated By:{" "}
            <span style={{ textDecoration: "underline" }}>Manager</span>
          </p>
          <p style={{ textAlign: "right" }}>
            Approved By:{" "}
            <span style={{ textDecoration: "underline" }}>Manager</span>
          </p>
        </div>
      </div>
    </div>
  );
};

export default DataTable;
