import { useState, useMemo, useEffect } from "react";
import {
  Table,
  TableHeader,
  TableColumn,
  TableBody,
  TableRow,
  TableCell,
  Pagination,
  getKeyValue,
} from "@nextui-org/react";
// import { users } from "./data";

export default function ReportsTable({ data }) {
  const [page, setPage] = useState(1);
  const rowsPerPage = 15;

  const pages = Math.ceil(data.length / rowsPerPage);

  const items = useMemo(() => {
    const start = (page - 1) * rowsPerPage;
    const end = start + rowsPerPage;

    return data.slice(start, end);
  }, [page, data]);

  const totalProfit = data.reduce((acc, item) => acc + item.totalAmount, 0);

  return (
    <>
      <Table
        isStriped
        aria-label="Example table with client side pagination"
        bottomContent={
          <div className="flex flex-col w-full justify-center">
            <Pagination
              isCompact
              showControls
              showShadow
              color="secondary"
              page={page}
              total={pages}
              onChange={(page) => setPage(page)}
            />
            <div>
              <div className="w-full flex items-center justify-end px-32 mt-4">
                <p style={{ textAlign: "right" }}>
                  Total Profit:{" "}
                  <span style={{ textDecoration: "underline" }}>
                  ₱ {totalProfit}
                  </span>
                </p>
              </div>
              <div className="w-full flex items-center justify-end px-28">
                <div>
                  <p style={{ textAlign: "right" }}>
                    Generated By:{" "}
                    <span style={{ textDecoration: "underline" }}>Manager</span>
                  </p>
                  <p style={{ textAlign: "right" }}>
                    Approved By:{" "}
                    <span style={{ textDecoration: "underline" }}>Manager</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        }
      >
        <TableHeader>
          <TableColumn key="date">DATE</TableColumn>
          <TableColumn key="quantity">QUANTITY</TableColumn>
          <TableColumn key="roomType">ROOM TYPE</TableColumn>
          <TableColumn key="amount">AMOUNT</TableColumn>
          <TableColumn key="totalAmount">TOTAL AMOUNT</TableColumn>
        </TableHeader>
        <TableBody items={items}>
          {(item) => (
            <TableRow key={item.name}>
              {(columnKey) => (
                <TableCell>{getKeyValue(item, columnKey)}</TableCell>
              )}
            </TableRow>
          )}
        </TableBody>
      </Table>
    </>
  );
}
